name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: 'Create env file'
      run: |
        touch .env.local
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env.local
        echo MAILER_DSN=${{ secrets.MAILER_DSN }} >> .env.local

    - name: Transferir HTML para a VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.IP }} # Endereço IP da sua VM
        username: ubuntu # Nome de usuário da sua VM
        key: ${{ secrets.SSH_PRIVATE_KEY }} # Chave SSH privada
        source: "*" # Caminho relativo do arquivo HTML (se estiver no diretório de trabalho)
        target: "/var/www/ajuda-tche/" # Caminho na sua VM onde você deseja que o arquivo seja transferido

   
